language: c
compiler: gcc
addons:
    apt:
        packages:
            - python3
            - autoconf
            - automake
            - autopoint
            - libtool
            - gettext
            - libidn11
            - libidn11-dev
            - libidn2-0
            - libidn2-0-dev
            - libicu48
            - libicu-dev
            - libunistring0
            - libunistring-dev

script:
    - DIR=`pwd`
    - cd linter
    - ./pslint_selftest.sh
    - ./pslint.py ../public_suffix_list.dat
    - cd $DIR
    - git clone --depth=1 --branch newfmt https://github.com/rockdaboot/libpsl
    - cd libpsl
    - echo "EXTRA_DIST =" >gtk-doc.make
    - echo "CLEANFILES =" >>gtk-doc.make
    - autoreconf --install --force --symlink
    - OPTIONS="--with-psl-file=$DIR/public_suffix_list.dat --with-psl-testfile=$DIR/tests/tests.txt"
# Test PSL data with libicu (IDNA2008 UTS#46)
    - ./configure -C --enable-runtime=libicu --enable-builtin=libicu $OPTIONS && make clean && make check -j4
# TEST PSL data with libidn2 (IDNA2008)
#    - ./configure -C --enable-runtime=libidn2 --enable-builtin=libidn2 $OPTIONS && make clean && make check -j4
# TEST PSL data with libidn (IDNA2003)
#    - ./configure -C --enable-runtime=libidn --enable-builtin=libidn $OPTIONS && make clean && make check -j4
